/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

//import  AssetumBlockchain.core.EventoCurricular;
import  AssetumBlockchain.core.User;
import blockchain.utils.Block;
import blockchain.utils.BlockChain;
import blockchain.utils.MerkleTree;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import p2p.IremoteP2P;
import p2p.NodeP2PGui;
import p2p.P2Plistener;
import utils.UtilizadorData;

/**
 * Interface gráfica que permite gerir eventos curriculares e armazená-los numa
 * blockchain
 *
 * @author Catarina - Miguel
 */
public class AssetumGUI extends javax.swing.JFrame implements P2Plistener {

    // Nome do ficheiro onde a blockchain será armazenada
    public static String fileBlockChain = "blockchain.obj";

    // Nome do ficheiro onde a Merkle Tree será armazenada
    public static String fileMerkleTree = "merkletree.obj";

    // Lista temporária para armazenar os eventos curriculares antes de criar o bloco
  //  private List<EventoCurricular> temporaryEvents = new ArrayList<>();

    // Instância da Merkle Tree
    MerkleTree mt;

    // Utilizador atualmente autenticado
    User myUser = null;

    // Endereço do utilizador
    String address = null;

    // Objeto remoto para comunicação com outro sistema (utilizando um serviço remoto)
    IremoteP2P myremoteObj;

    /**
     * Cria a interface gráfica para o Curriculum Digital, inicializa
     * componentes, e carrega a blockchain do ficheiro
     */
    public AssetumGUI() {
        initComponents();

        try {
            // Carrega a Merkle Tree do ficheiro e atualiza a lista de eventos temporários
        //    mt = MerkleTree.loadFromFile(fileMerkleTree);
          //  temporaryEvents = mt.getElements();

            // Atualiza a lista gráfica dos eventos que ainda não foram salvos na blockchain
//            updateListEventos();
        } catch (Exception e) {
            // Imprimir erro caso aconteça
            System.out.println(e);
        }

    }

    /**
     * Cria a interface gráfica associada a um utilizador específico
     *
     * @param u O utilizador autenticado
     * @param addr Endereço para comunicação remota
     */
    public AssetumGUI(User u, String addr) {
        this();
        this.myUser = u;
        this.txtFrom.setText(u.getName());
        this.address = addr;

        try {
            // Obtém o endereço do nó para a comunicação remota
            this.myremoteObj = (IremoteP2P) Naming.lookup(address);

            // Carrega a drop down com os Users
            preencherDropdown();

        } catch (NotBoundException ex) {
            Logger.getLogger(AssetumGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(AssetumGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AssetumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpTransaction = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnTransaction = new javax.swing.JPanel();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        txtValue1 = new javax.swing.JTextField();
        txtValue2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEventos = new javax.swing.JTextArea();
        btRegister = new javax.swing.JButton();
        pnUsersBalance = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btCurriculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCurriculo = new javax.swing.JTextArea();
        dropDownUsers = new javax.swing.JComboBox<>();
        jTabbedPane5 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transações/Currículos");
        setResizable(false);

        tpTransaction.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpTransactionStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnTransaction.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        txtFrom.setEditable(false);
        txtFrom.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtFrom.setBorder(javax.swing.BorderFactory.createTitledBorder("De"));
        pnTransaction.add(txtFrom);

        txtTo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtTo.setBorder(javax.swing.BorderFactory.createTitledBorder("Para"));
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });
        pnTransaction.add(txtTo);

        txtValue.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtValue.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento Curricular"));
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });
        pnTransaction.add(txtValue);
        txtValue.getAccessibleContext().setAccessibleName("Distrito");
        txtValue.getAccessibleContext().setAccessibleDescription("");

        txtValue1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtValue1.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento Curricular"));
        txtValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue1ActionPerformed(evt);
            }
        });
        pnTransaction.add(txtValue1);

        txtValue2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtValue2.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento Curricular"));
        txtValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValue2ActionPerformed(evt);
            }
        });
        pnTransaction.add(txtValue2);

        jTextField1.setText("jTextField1");
        pnTransaction.add(jTextField1);
        jTextField1.getAccessibleContext().setAccessibleName("Distrito");

        jPanel1.add(pnTransaction, java.awt.BorderLayout.NORTH);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/graduado.png"))); // NOI18N

        txtEventos.setColumns(20);
        txtEventos.setRows(5);
        jScrollPane2.setViewportView(txtEventos);

        btRegister.setBackground(new java.awt.Color(153, 0, 153));
        btRegister.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        btRegister.setForeground(new java.awt.Color(255, 255, 255));
        btRegister.setText("Registar Ativo");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        tpTransaction.addTab("Transação", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/habilitações.png")), jPanel1); // NOI18N

        btCurriculo.setBackground(new java.awt.Color(136, 175, 232));
        btCurriculo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        btCurriculo.setForeground(new java.awt.Color(51, 51, 51));
        btCurriculo.setText("Lista de Ativos");
        btCurriculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCurriculoActionPerformed(evt);
            }
        });

        txtCurriculo.setEditable(false);
        txtCurriculo.setBackground(new java.awt.Color(255, 255, 255));
        txtCurriculo.setColumns(20);
        txtCurriculo.setLineWrap(true);
        txtCurriculo.setRows(5);
        jScrollPane1.setViewportView(txtCurriculo);

        dropDownUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropDownUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btCurriculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dropDownUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btCurriculo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btCurriculo.getAccessibleContext().setAccessibleName("Lista de Ativos");

        javax.swing.GroupLayout pnUsersBalanceLayout = new javax.swing.GroupLayout(pnUsersBalance);
        pnUsersBalance.setLayout(pnUsersBalanceLayout);
        pnUsersBalanceLayout.setHorizontalGroup(
            pnUsersBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnUsersBalanceLayout.setVerticalGroup(
            pnUsersBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tpTransaction.addTab("Ativos", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/educacao.png")), pnUsersBalance); // NOI18N
        tpTransaction.addTab("tab3", jTabbedPane5);

        getContentPane().add(tpTransaction, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed

        // Criar uma nova thread para execução assíncrona
        new Thread(() -> {
            try {
                // Obter a lista de transações remotas
                List<String> blockTransactions = myremoteObj.getTransactions();
                System.out.println(myremoteObj.getTransactionsSize());
                
                
                
                
                // Criar um novo utilizador destino a partir do campo "Para"
                User toUser = new User(txtTo.getText());
                toUser.loadPublic();

                // Criar um novo evento curricular
                //EventoCurricular t = new EventoCurricular(myUser, toUser, txtValue.getText());

                // Adicionar o evento à lista de transações remotas
              //  myremoteObj.addTransaction(t.toString());

                // Adicionar o evento à lista local temporária
             //   blockTransactions.add(t.toString());

                // Verificar se existem transações suficientes para criar um bloco
                if (blockTransactions.size() >= 4) {

                    // Desativar o botão de registo de evento enquanto processa
                    btRegister.setEnabled(false);

                    // Criar o bloco com o hash anterior e as transações
                    Block b = new Block(myremoteObj.getBlockchainLastHash(), blockTransactions);

                    // Remover as transações utilizadas
                    myremoteObj.removeTransactions(blockTransactions);

                    // Minerar o bloco
                    int zeros = 3; // Número de zeros para a dificuldade
                    int nonce = myremoteObj.mine(b.getMinerData(), zeros);

                    // Atualizar o nonce do bloco
                    b.setNonce(nonce, zeros);

                    // Adicionar o bloco à blockchain remota
                    myremoteObj.addBlock(b);

                    // Limpar a lista temporária local de transações
                    //blockTransactions.clear();

                    // Exibir uma mensagem de sucesso
                    JOptionPane.showMessageDialog(this, "Bloco minerado e adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(AssetumGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao registar evento ou minerar bloco: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            } finally {
                // Reativar o botão de registo
                btRegister.setEnabled(true);
            }
        }).start();

    }//GEN-LAST:event_btRegisterActionPerformed


    private void tpTransactionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpTransactionStateChanged

    }//GEN-LAST:event_tpTransactionStateChanged

    private void btCurriculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCurriculoActionPerformed

        // Pega o nome selecionado na dropdown
        String nomeSelecionado = (String) dropDownUsers.getSelectedItem();

        try {

            // Chama o método remoto para obter as transações temporárias
            List<String> transacoesTemporarias = myremoteObj.getTransactions();

            // Chama o método remoto para obter as transações da blockchain
            List<String> transacoes = myremoteObj.getBlockchainTransactions();

            // Combina as duas listas de transações
            List<String> todasTransacoes = new ArrayList<>();

            todasTransacoes.addAll(transacoes);

            // Se a lista de transações temporárias tiver menos de 4 eventos, adiciona as transações temporárias
            if (transacoesTemporarias.size() < 4) {
                todasTransacoes.addAll(transacoesTemporarias);
            }

            // Filtra as transações que acabem com o nome selecionado
            List<String> curriculo = procuracurriculo(todasTransacoes, nomeSelecionado);

            // Limpa o conteúdo atual da JTextArea
            txtCurriculo.setText("");

            // Adiciona as transações filtradas na JTextArea
            for (String transacao : curriculo) {
                // Adiciona uma transação de cada vez à JTextArea
                txtCurriculo.append(transacao + "\n");  // "\n" adiciona uma nova linha após cada transação
            }

        } catch (RemoteException e) {
            e.printStackTrace();  // Tratar o erro de comunicação remota
        }


    }//GEN-LAST:event_btCurriculoActionPerformed


    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed

    }//GEN-LAST:event_txtValueActionPerformed

    private void txtValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue1ActionPerformed

    private void txtValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValue2ActionPerformed

    /**
     * Método main que inicializa a GUI da aplicação
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssetumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssetumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssetumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssetumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssetumGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCurriculo;
    private javax.swing.JButton btRegister;
    private javax.swing.JComboBox<String> dropDownUsers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnTransaction;
    private javax.swing.JPanel pnUsersBalance;
    private javax.swing.JTabbedPane tpTransaction;
    private javax.swing.JTextArea txtCurriculo;
    private javax.swing.JTextArea txtEventos;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtValue;
    private javax.swing.JTextField txtValue1;
    private javax.swing.JTextField txtValue2;
    // End of variables declaration//GEN-END:variables

//    /**
//     * Atualiza a lista gráfica dos eventos temporários Este método atualiza a
//     * interface gráfica para refletir os eventos curriculares armazenados
//     * temporariamente.
//     */
//    public void updateListEventos() {
//        // Cria um modelo para a lista
//        DefaultListModel model = new DefaultListModel();
//        // Adiciona todos os eventos temporários à lista gráfica
//        for (EventoCurricular elem : temporaryEvents) {
//            model.addElement(elem.toString()); // Adiciona a representação em string do evento
//        }
//        // Atualiza o modelo da lista gráfica com os eventos
//        lsteventos.setModel(model);
//    }
    /**
     * Preenche a dropdown de utilizadores com os dados obtidos de um sistema
     * remoto. Este método faz uma chamada remota para obter a lista de
     * utilizadores e preenche a dropdown com os nomes.
     */
    private void preencherDropdown() {
        try {
            // Chama o método remoto para obter a lista de utilizadores
            ArrayList<UtilizadorData> utilizadores = (ArrayList<UtilizadorData>) myremoteObj.getUsers();

            // Cria um DefaultComboBoxModel para preencher a dropdown
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

            // Adiciona o nome de cada utilizador ao modelo da dropdown
            for (UtilizadorData utilizador : utilizadores) {
                model.addElement(utilizador.getNome()); // Adiciona o nome do utilizador
            }

            // Atualiza o modelo da dropdown com a lista de utilizadores
            dropDownUsers.setModel(model);

        } catch (RemoteException e) {
            // Trata erro de comunicação remota, caso haja algum problema na chamada remota
            e.printStackTrace();
        }
    }

    /**
     * Função que procura transações com o nome no final. Este método procura
     * transações que terminam com o nome especificado e retorna uma lista de
     * transações encontradas.
     *
     * @param transacoes Lista de transações para procurar
     * @param nomeSelecionado Nome a ser procurado no final das transações
     * @return Lista de transações que terminam com o nome especificado
     */
    private List<String> procuracurriculo(List<String> transacoes, String nomeSelecionado) {
        // Lista onde serão armazenadas as transações que atendem ao critério
        List<String> transacoesEncontradas = new ArrayList<>();

        // Procura por transações que terminam com o nomeSelecionado
        for (String transacao : transacoes) {
            // Verifica se a transação termina com o nome especificado
            if (transacao.endsWith(nomeSelecionado)) {
                transacoesEncontradas.add(transacao); // Adiciona à lista de transações encontradas
            }
        }
        // Retorna a lista de transações encontradas
        return transacoesEncontradas;
    }

    @Override
    public void onException(Exception ex, String message) {

    }

    @Override
    public void onMessage(String title, String message) {

    }

    @Override
    public void onStartRemote(String message) {

    }

    @Override
    public void onConect(String address) {

    }

    @Override
    public void onTransaction(String transaction) {
        try {
            onMessage("Transaction ", transaction);
            String txt = "";
            List<String> tr = myremoteObj.getTransactions();
            for (String string : tr) {
                txt += string + "\n";
            }
            txtEventos.setText(txt);
            tpTransaction.setSelectedComponent(pnTransaction);
        } catch (RemoteException ex) {
            onException(ex, "on transaction");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onStartMining(String message, int zeros) {

    }

    @Override
    public void onStopMining(String message, int nonce) {

    }

    @Override
    public void onNounceFound(String message, int nonce) {

    }

    @Override
    public void onBlockchainUpdate(BlockChain b) {

    }
}
