package GUI;

import  AssetumBlockchain.core.User;
import blockchain.utils.BlockChain;
import java.io.File;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import p2p.IremoteP2P;
import p2p.NodeP2PGui;
import p2p.OremoteP2P;
import p2p.P2Plistener;
import utils.RMI;

/**
 * Classe responsável pela GUI de Login, permitindo que os utilizadores se
 * registem e façam login no sistema
 *
 * @author Catarina - Miguel
 */
public class Login extends javax.swing.JFrame implements P2Plistener{

    // Lista para os nomes de utilizador que tem conta criada
    ArrayList<String> usersname = new ArrayList<>();

    // Objeto remoto usado para interações com outros nós na rede P2P
    OremoteP2P myremoteObject;

    /**
     * Construtor da classe que inicializa a interface gráfica.
     */
    public Login() {
        initComponents();

        // Atualiza a lista de Users 
        updateUsersList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogin = new javax.swing.JTabbedPane();
        pnlogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLoginUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLoginPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPublicKey = new javax.swing.JTextArea();
        pnregister = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtRegisterUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegisterPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        pnconexao = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtendereco = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btConectar = new javax.swing.JButton();
        pnusers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente ");
        setResizable(false);

        pnLogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pnLoginStateChanged(evt);
            }
        });

        pnlogin.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel1.setText("Username");

        txtLoginUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel2.setText("Password");

        txtLoginPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/perfil.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoginPass))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12))
        );

        btLogin.setBackground(new java.awt.Color(153, 0, 153));
        btLogin.setFont(new java.awt.Font("Tw Cen MT", 2, 48)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        txtPublicKey.setEditable(false);
        txtPublicKey.setBackground(new java.awt.Color(204, 204, 204));
        txtPublicKey.setColumns(20);
        txtPublicKey.setRows(5);
        jScrollPane1.setViewportView(txtPublicKey);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnlogin.add(jPanel2, java.awt.BorderLayout.WEST);

        pnLogin.addTab("Login", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/login_icon.png")), pnlogin); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel3.setText("Username");

        txtRegisterUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel4.setText("Password");

        txtRegisterPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/pessoas.png"))); // NOI18N

        btRegister.setBackground(new java.awt.Color(136, 175, 232));
        btRegister.setFont(new java.awt.Font("Tw Cen MT", 2, 48)); // NOI18N
        btRegister.setText("Registar");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnregisterLayout = new javax.swing.GroupLayout(pnregister);
        pnregister.setLayout(pnregisterLayout);
        pnregisterLayout.setHorizontalGroup(
            pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnregisterLayout.createSequentialGroup()
                .addGroup(pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnregisterLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegisterPass, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnregisterLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel10))
                    .addGroup(pnregisterLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        pnregisterLayout.setVerticalGroup(
            pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnregisterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnregisterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(pnregisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegisterPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pnLogin.addTab("Registo", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/registo_icon.png")), pnregister); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CONEXÃO SERVIDOR");

        txtendereco.setColumns(20);
        txtendereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtendereco.setRows(5);
        jScrollPane5.setViewportView(txtendereco);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel11.setText("Endereço");

        btConectar.setBackground(new java.awt.Color(136, 175, 232));
        btConectar.setFont(new java.awt.Font("Tw Cen MT", 2, 48)); // NOI18N
        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnconexaoLayout = new javax.swing.GroupLayout(pnconexao);
        pnconexao.setLayout(pnconexaoLayout);
        pnconexaoLayout.setHorizontalGroup(
            pnconexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnconexaoLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addGroup(pnconexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                .addGap(254, 254, 254))
            .addGroup(pnconexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnconexaoLayout.setVerticalGroup(
            pnconexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnconexaoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnLogin.addTab("Conexão", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/conexao.png")), pnconexao, ""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("UTILIZADORES");

        listaUsers.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        listaUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaUsersValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaUsers);

        javax.swing.GroupLayout pnusersLayout = new javax.swing.GroupLayout(pnusers);
        pnusers.setLayout(pnusersLayout);
        pnusersLayout.setHorizontalGroup(
            pnusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnusersLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnusersLayout.setVerticalGroup(
            pnusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnusersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );

        pnLogin.addTab("Utilizadores", new javax.swing.ImageIcon(getClass().getResource("/projetocd/imagens/habilitações.png")), pnusers, ""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed

        try {
            
            // Obtém o endereço do nó para a comunicação remota
            String endereco = txtendereco.getText().trim();
            IremoteP2P myremoteObject = (IremoteP2P) Naming.lookup(endereco);
            
                      
            User u = new User(txtLoginUser.getText());
            
            // Carrega os dados do utilizador a partir da senha inserida
            u.load(new String(txtLoginPass.getPassword()));
            // Converte a chave pública do utilizador para Base64 e exibe-a na interface
            String pub = Base64.getEncoder().encodeToString(u.getPub().getEncoded());
            txtPublicKey.setText(pub);
            
            
            
            boolean sucessologin = myremoteObject.login(txtLoginUser.getText(), txtLoginPass.getPassword());

            
            // Verifica se o registo foi bem-sucedido
            if (sucessologin) {
                // Informa o sucesso da criação do utilizador
                JOptionPane.showMessageDialog(this, "Login efetuado com sucesso!");
                // Abre a interface principal do sistema com o utilizador autenticado
                new AssetumGUI(u, endereco).setVisible(true);
                setVisible(false);
                
                
            } else {
                // Informa o insucesso do login 
                JOptionPane.showMessageDialog(this, "Erro ao fazer login");
            }
                        
        } catch (Exception ex) {
            // Exibe um erro caso as credenciais estejam incorretas ou ocorram outros problemas
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void pnLoginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pnLoginStateChanged

    }//GEN-LAST:event_pnLoginStateChanged

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed

        try {

            // Obtém o endereço do nó para a comunicação remota
            String endereco = txtendereco.getText().trim();
            IremoteP2P myremoteObj = (IremoteP2P) Naming.lookup(endereco);

            // Chama o método de registo no servidor remoto
            boolean sucesso = myremoteObj.register(txtRegisterUser.getText(), txtRegisterPass.getPassword());

            // Verifica se o registo foi bem-sucedido
            if (sucesso) {
                // Informa o sucesso da criação do utilizador
                JOptionPane.showMessageDialog(this, "Utilizador criado com sucesso");
            } else {
                // Informa o insucesso da criação do utilizador
                JOptionPane.showMessageDialog(this, "Erro ao criar utilizador");
            }

            // Limpa os campos
            txtRegisterUser.setText("");
            txtRegisterPass.setText("");
            

        } catch (Exception ex) {
            // Exibe um erro caso ocorra um problema ao criar o utilizador
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btRegisterActionPerformed

    private void listaUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaUsersValueChanged
        // Verifica se um item foi selecionado na lista de users
        if (listaUsers.getSelectedIndex() != -1) {
            // Escreve o nome do user selecionado no login 
            txtLoginUser.setText(listaUsers.getSelectedValue());
        }
    }//GEN-LAST:event_listaUsersValueChanged

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed

        try {
            // Obtém o endereço do servidor inserido pelo utilizador
            String enderecofornecido = txtendereco.getText().trim();

            // Verifica se o endereço começa com "//" (formato correto)
            if (enderecofornecido.isEmpty() || !enderecofornecido.startsWith("//")) {
                JOptionPane.showMessageDialog(this, "Por favor, insira o endereço completo no formato //IP:PORTA/ObjetoRemoto", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Tenta obter o objeto remoto do servidor
            IremoteP2P node = (IremoteP2P) RMI.getRemote(enderecofornecido);

            // Aqui, o cliente envia o seu objeto (nó) para o servidor
            // A ideia é que o servidor adicione este nó à sua rede
            node.addNode(node); // O servidor deve ter este método para adicionar nós à sua rede

            // Agora que estamos conectados, podemos exibir uma mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Conexão bem-sucedida ao servidor: " + enderecofornecido, "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            // Trata erros de conexão e exibe mensagem de erro
            JOptionPane.showMessageDialog(this, "Erro ao conectar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btConectarActionPerformed

    /**
     * Método para obter os nomes de todos os utilizadores com conta criada
     */
    public void getNameUsers() {

        usersname.clear();

        // Define o caminho para a root do projeto
        String projectRootPath = System.getProperty("user.dir");

        // Cria um objeto File que representa a root do projeto
        File projectRoot = new File(projectRootPath);

        // Obtém a lista de ficheiros e diretórios
        File[] files = projectRoot.listFiles();

        if (files != null) {
            for (File file : files) {
                // Verifica se é um ficheiro e se a extensão é .priv
                if (file.isFile() && file.getName().endsWith(".priv")) {
                    usersname.add(file.getName().replace(".priv", ""));
                }
            }
        } else {
            System.out.println("Não foi possível listar os ficheiros.");
        }
    }

    /**
     * Método para atualizar o conteúdo do componente que mostra a lista de
     * users com conta criada
     */
    public void updateUsersList() {
        getNameUsers();

        // Criação de um modelo para exibir a lista de users
        DefaultListModel model = new DefaultListModel();
        for (String elem : usersname) {
            model.addElement(elem);
        }
        // Define o modelo da lista gráfica
        listaUsers.setModel(model);
    }

    /**
     * Método main que inicializa a GUI de Login
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listaUsers;
    private javax.swing.JTabbedPane pnLogin;
    private javax.swing.JPanel pnconexao;
    private javax.swing.JPanel pnlogin;
    private javax.swing.JPanel pnregister;
    private javax.swing.JPanel pnusers;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    private javax.swing.JTextArea txtPublicKey;
    private javax.swing.JPasswordField txtRegisterPass;
    private javax.swing.JTextField txtRegisterUser;
    private javax.swing.JTextArea txtendereco;
    // End of variables declaration//GEN-END:variables

   

    /**
     * Atualiza a interface com os detalhes da rede e exibe os nós conectados.
     *
     * @param address Endereço do nó que se conectou
     */    
    @Override
    public void onConect(String address) {
        try {
            // Obtém a lista de nós conectados
            List<IremoteP2P> net = myremoteObject.getNetwork();
            String txt = "";
            // Itera sobre os nós conectados e adiciona os seus endereços ao texto
            for (IremoteP2P iremoteP2P : net) {
                txt += iremoteP2P.getAdress() + "\n";
            }
        } catch (RemoteException ex) {
            onException(ex, "On conect");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

  
    // Métodos não implementados, mas definidos na interface:
     @Override
    public void onException(Exception ex, String message) {        
    }

    @Override
    public void onMessage(String title, String message) {        
    }

    @Override
    public void onStartRemote(String message) {        
    }
    
    @Override
    public void onTransaction(String transaction) {        
    }

    @Override
    public void onStartMining(String message, int zeros) {        
    }

    @Override
    public void onStopMining(String message, int nonce) {       
    }

    @Override
    public void onNounceFound(String message, int nonce) {     
    }

    @Override
    public void onBlockchainUpdate(BlockChain b) {        
    }
}
